# Generated by Django 4.2.16 on 2026-02-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_price_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stripe_customer_id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='blog_level',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro')], default='free', max_length=20),
        ),
    ]
