# Generated by Django 4.2.16 on 2026-02-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
