# Generated by Django 4.2.16 on 2026-02-07 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('free_content', models.TextField(blank=True, help_text='誰でも読める導入文', null=True, verbose_name='無料公開部分')),
                ('premium_content', models.TextField(blank=True, help_text='サブスクユーザーのみ閲覧可能', null=True, verbose_name='有料コンテンツ')),
                ('is_premium', models.BooleanField(default=False, verbose_name='有料記事')),
                ('is_published', models.BooleanField(default=True, verbose_name='公開状態')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='公開日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '記事',
                'verbose_name_plural': '記事',
                'ordering': ['-published_at'],
            },
        ),
    ]
